version: '2'

services:
    web_tools:
        container_name: web_tools
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "8080:8080"
        volumes:
            - .:/code
        working_dir: /code
        command: tail -f /dev/null
